# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Publish docs

on:
  release:
    types: [created]

jobs:
  publish-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ssh-key: ${{ secrets.LIONEL_BOT_SSH }}
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: yarn
      - run: yarn docs:build
      - run: cd docs/.vitepress/dist
      - run: git add -A
      - run: git config --global user.email "lionel-bot@aventyret.com"
      - run: git config --global user.name "Lionel CI bot"
      - run: git commit -m "Publish docs"
      - run: "git push -f git@github.com:$GITHUB_REPOSITORY.git HEAD:gh-pages"
      - run: cd -
