# This workflow will build and publish the latest docs at each release
name: Publish docs

on:
  release:
    types: [created]

jobs:
  publish-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.LIONEL_BOT_SSH }}
      - uses: actions/setup-node@v2
        with:
          node-version: 18
      - uses: pnpm/action-setup@v2
        with:
          version: 7
          run_install: false
      - name: 'Build docs'
        run: |
          pnpm install --frozen-lockfile
          cd ./packages/docs && pnpm run build
      - name: 'Push docs to gh-pages branch'
        working-directory: ./packages/docs/.vitepress/dist
        run: |
          pwd
          git init -b main
          git add -A
          git config --global user.email "lionel-bot@aventyret.com"
          git config --global user.name "lionel-bot"
          git commit -m "Publish docs"
          git push -f git@github.com:$GITHUB_REPOSITORY.git HEAD:gh-pages
