# This workflow will build and publish the latest docs at each release
name: Publish docs

on:
  release:
    types: [created]

jobs:
  publish-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ssh-key: ${{ secrets.LIONEL_BOT_SSH }}
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: 'Build docs'
        run: |
          yarn
          yarn docs:build
      - name: 'Push docs to gh-pages branch'
        working-directory: ./docs/.vitepress/dist
        run: |
          pwd
          git init -b main
          git add -A
          git config --global user.email "lionel-bot@aventyret.com"
          git config --global user.name "lionel-bot"
          git commit -m "Publish docs"
          git push -f https://lionel-bot:$GITHUB_TOKEN@github.com/$GITHUB_REPOSITORY.git HEAD:gh-pages
